// Generated by CoffeeScript 2.5.1
module.exports = {
  array_flatten: function(arr, depth = -1) {
    var i, j, ref, ret;
    ret = [];
    for (i = j = 0, ref = arr.length; (0 <= ref ? j < ref : j > ref); i = 0 <= ref ? ++j : --j) {
      if (Array.isArray(arr[i])) {
        if (depth === 0) {
          ret.push(...arr[i]);
        } else {
          ret.push(...module.exports.array_flatten(arr[i], depth - 1));
        }
      } else {
        ret.push(arr[i]);
      }
    }
    return ret;
  }
};
